### ISSUE TITLE
Incompatibility with WP Ultimo

### ISSUE THREAD

**Issue by urbanoantunes** [woocommerce/woocommerce-google-analytics-integration#142] opened 2019-03-21 20:33 UTC
#### What I expected

Using Google Analytics Integration Plugin and WP Ultimo Plugin, on a WPMU network.

When a administrator user from a sub-site try to view this page:
https://cloudstore.pt/finalizar-compra/encomenda-recebida/3477/?key=wc_order_5c93f232f41a2
they got a blank page.
(This is the main site of the network)

If a super-admin try to view this page, it loads correctly.

If I deactivate the Google Analytics Integration plugin, the problem stops.

I got this on the error.log:

[21-Mar-2019 20:01:45 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_sku() on boolean in /home/cloudstore/public_html/wp-content/plugins/woocommerce-google-analytics-integration/includes/class-wc-google-analytics-js.php:375
Stack trace:
#0 /home/cloudstore/public_html/wp-content/plugins/woocommerce-google-analytics-integration/includes/class-wc-google-analytics-js.php(307): WC_Google_Analytics_JS->add_item_classic(Object(WC_Order), Object(WC_Order_Item_Product))
#1 /home/cloudstore/public_html/wp-content/plugins/woocommerce-google-analytics-integration/includes/class-wc-google-analytics-js.php(283): WC_Google_Analytics_JS->add_transaction_classic(Object(WC_Order))
#2 /home/cloudstore/public_html/wp-content/plugins/woocommerce-google-analytics-integration/includes/class-wc-google-analytics.php(332): WC_Google_Analytics_JS->add_transaction(Object(WC_Order))
#3 /home/cloudstore/public_html/wp-content/plugins/woocommerce-google-analytics-integration/includes/class-wc-google-analytics.php(293): WC_Google_Analytics->get_ecommerce_trackin in /home/cloudstore/public_html/wp-content/plugins/woocommerce-google-analytics-integration/includes/class-wc-google-analytics-js.php on line 375

The user administrator of a sub-site should be able to see this page
https://cloudstore.pt/finalizar-compra/encomenda-recebida/3477/?key=wc_order_5c93f232f41a2
instead of getting a blank page

#### What happened instead

User administrator of sub-sites get a blank page

This can only be tested with both plugins installed and WC addon for WP Ultimo.

Is there any feedback we can provide to WP Ultimo developer so they can check this out?

Thanks for your help!

#### Steps to reproduce the issue

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by urbanoantunes** [comment] 2019-03-21 20:47
FYI: Just discovered if I disable Purchase Transactions and Add to Cart Events from the main site, Administrators from sub-sites can see the order-confirmation page again.

**Comment by raphawa** [comment] 2020-07-15 19:00
Hello
I'm facing same issue how did you disable Purchase Transactions and Add to Cart Events from the main site?
Thanks

**Comment by budzanowski** [comment] 2021-09-14 03:57
Some Issues that look similar have been fixed already. Hopefully, this error no longer exists, this is why I am closing the Issue. In case this situation is different and the problem is still there please reopen the issue.

**Closed by budzanowski** 2021-09-14 03:57 UTC
Labels: priority: low, type: bug
