### ISSUE TITLE
GA reporting duplicate sales

### ISSUE THREAD

**Issue by ldr2273** [woocommerce/woocommerce-google-analytics-integration#120] opened 2018-05-17 05:02 UTC
1163667-zen
1423824-zen

Google Analytics (https://woocommerce.com/products/woocommerce-google-analytics/) is recording duplicate sales from WooCommerce. Here's an example: https://snag.gy/PXLQUZ.jpg. The quantity should be "1" and amount "$39.95."

This seems to be happening randomly, and one possible theory that came up was that the duplicate logging was occurring when customers visit the Order Received page/thank you page twice: https://www.lunametrics.com/blog/2014/07/07/duplicate-transactions/

Is this the case with our extension? Or do we have code in place to prevent logging users from triggering the script on the confirmation page upon return to it? 

Any other thoughts at what could be causing this?

@mattyza - would you be able to provide any insight on this for me? TIA!

**Comment by mattyza** [comment] 2018-05-17 08:03
@ldr2273 - nothing jumps to mind, unfortunately. Pinging in @laurendavissmith on this as well.

**Comment by laurendavissmith** [comment] 2018-05-17 21:38
> Or do we have code in place to prevent logging users from triggering the script on the confirmation page upon return to it?

I'm not aware of any code to prevent that so that could possibly be what's going on, I've labeled it as a bug so we can take a look.

**Comment by ldr2273** [comment] 2018-05-17 22:27
Thanks! Very curious about this 👍

**Comment by amandasjackson** [comment] 2018-09-18 16:10
@woocommerce/extendables Adding 1423824-zen as it sounds like they are experiencing the same issue. They have narrowed it down to `most duplicate hits from mobile and tablet and a majority of them are from PayPal`

**Comment by Weeb** [comment] 2019-02-06 08:05
This also/still occurs with payment gateway "Klarna".
Mostly on mobile devices. My guess is that people after completing a purchase close their mobile browser and/or lock their device. After a while when they unlock and/or opening the browser again the last page loads once more and triggers the transaction again.

Perhaps check the database if transaction already has occured and if so don't send ga-transaction again on reload?

**Comment by pixeldom** [comment] 2019-06-15 15:09
Identical issue. Is this a low priority bug? Any workarounds?

**Comment by m155y** [comment] 2019-08-08 17:54
This was also reported in a forum support question recently, fyi: [Duplicate Tracking Issue in Google Analytics](https://wordpress.org/support/topic/duplicate-transaction-issue-in-google-analytics/)

**Comment by davidtzvi** [comment] 2019-08-31 21:49
I’d like to chime in as I’m experiencing the same issue with the occasional double counting of transactions. 

I’ve noticed it happen specifically when the user visited their completed checkout page a 2nd time. 

Having the plugin code prevent the same transaction to be counted twice would be help ensure Analytics reports aren’t inflated.

**Comment by mathiasnovas** [comment] 2019-09-25 16:26
Same issue. Any news? I'd love for the priority to be bumped up a little ✨

**Comment by Netty2** [comment] 2019-10-22 10:05
Hello. We have the same issue with our store. About 5-10% och transactions are reported twice. Anyone found a solution?

**Comment by willkidger** [comment] 2019-10-24 15:57
Same here, over the last couple of months around 10% of transactions, as above, being double counted. This has definitely only been a recent issue for us (didn't seem to affect our site in 2018 when this thread was started).

**Comment by anant1811** [comment] 2019-11-07 05:52
Also reported in 2461386-zen

**Comment by amityweb** [comment] 2019-12-10 13:25
Finally I find the issue reported! We too are having this. I have subitted support to WooCommerce and also on this forum https://wordpress.org/support/topic/duplicate-orders-in-google-analytics/

To me it looks like follow up ajax calls to the site (even the next day) are calling the analytics. The ajax calls are "/?wc-ajax=get_refreshed_fragments" and "/?wc-ajax=wc_stripe_get_cart_details"

Seems these calls result in analytics submitted again even though _ga_tracked=1

P.S. Completely disagree this is a [Pri] Low issue, it totally messes up sales reports in GA which is it vital for marketing strategies. Decisions being made on incorrect data.

**Comment by amityweb** [comment] 2019-12-10 13:26
Posting my Wordpress support form post here seen as this seems a better place to pursue the issue:


We had an order on 1st December and Google shows that, but then on the 2nd December Google shows the additional quantities being added to the order, 4 of them. So total of 5 quantities in total for this order in analytics. 

In the logs I can see on the order day, the main thank you page was called "/checkout/order-received/12345/", plus then two other background processes to WooCommerce, "/?wc-ajax=get_refreshed_fragments" and "/?wc-ajax=wc_stripe_get_cart_details". 

But then the following day, these two background processes are being called multiple times to the same order. But from different IP addresses 4 times. The main thank you page was not called again, like in a refresh. 

So something else is calling these background processes and the analytics is being submitted on these pages even though _ga_tracked=1, and I think the Google submission is IP session related, so it does not record it again from the same IP. So the 4 IPs relate to the 4 submissions the next day. 

So calling these URLs seems to allow the plugin to submit the data to google again. So if these processes are normal then we need to stop the analytics code being sent again, OR look into why and what is calling the background processes and stop those. It could be Stripe calling back. I have checked several of the orders with multiple quantities in Google and they are all stripe. 

For info, the IP addresses below do not match the customers, as we use Cloudflare. 



```
01/Dec/2019

162.158.154.43 - - [01/Dec/2019:21:40:24 +0000] "GET /checkout/order-received/12345/?key=wc_order_abcdefghijk&utm_nooverride=1 HTTP/1.1" 200 32537 "https://www.mydomain.com/checkout/" "Mozilla/5.0 (Linux; Android 9; SM-N975F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Mobile Safari/537.36"
162.158.154.43 - - [01/Dec/2019:21:40:27 +0000] "POST /?wc-ajax=get_refreshed_fragments HTTP/1.1" 200 4523 "https://www.mydomain.com/checkout/order-received/12345/?key=wc_order_abcdefghijk&utm_nooverride=1" "Mozilla/5.0 (Linux; Android 9; SM-N975F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Mobile Safari/537.36"
162.158.154.43 - - [01/Dec/2019:21:40:27 +0000] "POST /?wc-ajax=wc_stripe_get_cart_details HTTP/1.1" 200 952 "https://www.mydomain.com/checkout/order-received/12345/?key=wc_order_abcdefghijk&utm_nooverride=1" "Mozilla/5.0 (Linux; Android 9; SM-N975F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Mobile Safari/537.36"

02/Dec/2019

162.158.159.22 - - [02/Dec/2019:11:35:56 +0000] "POST /?wc-ajax=get_refreshed_fragments HTTP/1.1" 200 4521 "https://www.mydomain.com/checkout/order-received/12345/?key=wc_order_abcdefghijk&utm_nooverride=1" "Mozilla/5.0 (Linux; Android 9; SM-N975F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Mobile Safari/537.36"
162.158.159.22 - - [02/Dec/2019:11:35:56 +0000] "POST /?wc-ajax=wc_stripe_get_cart_details HTTP/1.1" 200 4345 "https://www.mydomain.com/checkout/order-received/12345/?key=wc_order_abcdefghijk&utm_nooverride=1" "Mozilla/5.0 (Linux; Android 9; SM-N975F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Mobile Safari/537.36"
162.158.159.22 - - [02/Dec/2019:11:36:50 +0000] "POST /?wc-ajax=wc_stripe_get_cart_details HTTP/1.1" 200 4345 "https://www.mydomain.com/checkout/order-received/12345/?key=wc_order_abcdefghijk&utm_nooverride=1" "Mozilla/5.0 (Linux; Android 9; SM-N975F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Mobile Safari/537.36"

162.158.154.121 - - [02/Dec/2019:13:56:58 +0000] "POST /?wc-ajax=get_refreshed_fragments HTTP/1.1" 200 4521 "https://www.mydomain.com/checkout/order-received/12345/?key=wc_order_abcdefghijk&utm_nooverride=1" "Mozilla/5.0 (Linux; Android 9; SM-N975F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Mobile Safari/537.36"
162.158.154.121 - - [02/Dec/2019:13:56:58 +0000] "POST /?wc-ajax=wc_stripe_get_cart_details HTTP/1.1" 403 4202 "https://www.mydomain.com/checkout/order-received/12345/?key=wc_order_abcdefghijk&utm_nooverride=1" "Mozilla/5.0 (Linux; Android 9; SM-N975F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Mobile Safari/537.36"
162.158.154.121 - - [02/Dec/2019:14:00:55 +0000] "POST /?wc-ajax=get_refreshed_fragments HTTP/1.1" 200 4521 "https://www.mydomain.com/checkout/order-received/12345/?key=wc_order_abcdefghijk&utm_nooverride=1" "Mozilla/5.0 (Linux; Android 9; SM-N975F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Mobile Safari/537.36"
162.158.154.121 - - [02/Dec/2019:14:00:55 +0000] "POST /?wc-ajax=wc_stripe_get_cart_details HTTP/1.1" 403 4202 "https://www.mydomain.com/checkout/order-received/12345/?key=wc_order_abcdefghijk&utm_nooverride=1" "Mozilla/5.0 (Linux; Android 9; SM-N975F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Mobile Safari/537.36"

162.158.158.15 - - [02/Dec/2019:15:48:28 +0000] "POST /?wc-ajax=get_refreshed_fragments HTTP/1.1" 200 4521 "https://www.mydomain.com/checkout/order-received/12345/?key=wc_order_abcdefghijk&utm_nooverride=1" "Mozilla/5.0 (Linux; Android 9; SM-N975F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Mobile Safari/537.36"
162.158.158.15 - - [02/Dec/2019:15:48:28 +0000] "POST /?wc-ajax=wc_stripe_get_cart_details HTTP/1.1" 403 4202 "https://www.mydomain.com/checkout/order-received/12345/?key=wc_order_abcdefghijk&utm_nooverride=1" "Mozilla/5.0 (Linux; Android 9; SM-N975F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Mobile Safari/537.36"

162.158.159.72 - - [02/Dec/2019:22:20:22 +0000] "POST /?wc-ajax=get_refreshed_fragments HTTP/1.1" 200 4521 "https://www.mydomain.com/checkout/order-received/12345/?key=wc_order_abcdefghijk&utm_nooverride=1" "Mozilla/5.0 (Linux; Android 9; SM-N975F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Mobile Safari/537.36"
162.158.159.72 - - [02/Dec/2019:22:20:22 +0000] "POST /?wc-ajax=wc_stripe_get_cart_details HTTP/1.1" 403 4202 "https://www.mydomain.com/checkout/order-received/12345/?key=wc_order_abcdefghijk&utm_nooverride=1" "Mozilla/5.0 (Linux; Android 9; SM-N975F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Mobile Safari/537.36"
```

**Comment by amityweb** [comment] 2019-12-10 13:34
P.S. I dont know if its related, but if you add the Date secondary dimension to the Sales Performance reports, we get dates that do not match orders on the site. Sometimes 2 days difference, which also means website to analytics sales on a per month basis do not match. So I am now wondering if this is related.

**Comment by amityweb** [comment] 2019-12-10 13:52
I can only find one place in the plugin that outputs the ecommerce analytics code, and the code looks like it would work OK. So unless there is an issue with get_post_meta( $order_id, '_ga_tracked', true ) when using the AJAX calls, I cant see how this would fail. Anyone else have an idea? Could  get_post_meta( $order_id, '_ga_tracked', true )  not equal 1 when using those AJAX calls? 

```
// Check if is order received page and stop when the products and not tracked
if ( is_order_received_page() && 'yes' === $this->ga_ecommerce_tracking_enabled ) {
	$order_id = isset( $wp->query_vars['order-received'] ) ? $wp->query_vars['order-received'] : 0;
	if ( 0 < $order_id && 1 != get_post_meta( $order_id, '_ga_tracked', true ) ) {
		$display_ecommerce_tracking = true;
		echo $this->get_ecommerce_tracking_code( $order_id );
	}
}
```

**Comment by amityweb** [comment] 2019-12-11 09:35
WooCommerce support have come back to me at first asking me to fix it, as they are prioritising paid plugins, but after I complain saying its on their list but its basically low priority. 

So the only thing I guess we can do if we cant fix it, is not use their plugin and use a 3rd party, as to m this is a various serious issue, to have the eCommerce sales reports all wrong.

**Comment by j-douglas-tf** [comment] 2020-05-03 19:56
> WooCommerce support have come back to me at first asking me to fix it, as they are prioritising paid plugins, but after I complain saying its on their list but its basically low priority.
> 
> So the only thing I guess we can do if we cant fix it, is not use their plugin and use a 3rd party, as to me this is a various serious issue, to have the eCommerce sales reports all wrong.

Dude - did you find a solution to this, or find a better plugin? I started using it today and it's recorded both transactions twice, so its completely uselses to me. Why would they flag this as a low priority bug, when it renders the whole thing unusable...

**Comment by amityweb** [comment] 2020-05-04 08:44
No nothing from the developers of this or WooCommerce even though I have add all this info above. 

We have had to create our own integration so we can manage the code.

**Comment by tc33** [comment] 2020-05-04 14:45
We were having issues with duplicate transactions being tracked by this extension on a client site. So we've implemented a fix which I'm intending to submit as a pull request in the next week or so. We have the fix in place on a production site at the moment and I'm just giving it a bit of time to check it resolves the issue first. It's been in place for 4 days with no duplicate transactions yet.

**Comment by j-douglas-tf** [comment] 2020-05-05 05:23
> We were having issues with duplicate transactions being tracked by this extension on a client site. So we've implemented a fix which I'm intending to submit as a pull request in the next week or so. We have the fix in place on a production site at the moment and I'm just giving it a bit of time to check it resolves the issue first. It's been in place for 4 days with no duplicate transactions yet.

Could you share it? I really need to get this fixed :(

**Comment by Netty2** [comment] 2020-05-07 05:35
Also looking forward to that fix!

**Comment by dougaitken** [comment] 2020-05-07 11:34
Hi @tc33 

Are you able to share this Pull Request? I can pass this on to the extension development team to take a look at getting merged into our plugin.

Thanks,

**Comment by tommyshellberg** [comment] 2020-05-07 12:45
Bumping to High.
Looks like this is a common problem with GA - sharing some sources on how the plugin can potentially tackle it:

https://www.thyngster.com/the-definitive-approach-for-preventing-duplicate-transactions-on-google-analytics-universal-customtask/

https://www.simoahava.com/analytics/prevent-google-analytics-duplicate-transactions-with-customtask/

**Comment by tc33** [comment] 2020-05-07 12:48
I'll create a pull request later today.

**Comment by tc33** [comment] 2020-05-07 20:30
Hi @dougaitken, would be good if you could nudge the development team to take a look. 

The issue seems to be that in certain scenarios some devices/browsers will reload a page locally (and re-run scripts) without a server request. For example, when a customer completes an order on their phone, then leaves the browser with the page still open. When they return to it several hours or days later the page gets reloaded without a full refresh.

The suggested fix is quite simple. In addition to the server side protection, we add a localStorage item with the order number and check against that before firing a second time.

**Comment by j-douglas-tf** [comment] 2020-05-08 06:40
> Hi @dougaitken, would be good if you could nudge the development team to take a look.
> 
> The issue seems to be that in certain scenarios some devices/browsers will reload a page locally (and re-run scripts) without a server request. For example, when a customer completes an order on their phone, then leaves the browser with the page still open. When they return to it several hours or days later the page gets reloaded without a full refresh.
> 
> The suggested fix is quite simple. In addition to the server side protection, we add a localStorage item with the order number and check against that before firing a second time.

this seems to be the same thing in my case, occurrences for me so far have been on tablet at random times after initial payment - so it must have been when they revisited the still opened thankyou page (confirmed by a second viewing of each in GA)

**Comment by Mic2005** [comment] 2020-07-03 13:05
Same issue here #follow

**Closed** 2020-07-23 08:43 UTC
Labels: [Pri] High, [Status] Has PR, [Type] Bug
