### ISSUE TITLE
Variable 'parent' product is being sent to Google with a $0.00 price

### ISSUE THREAD

**Issue by jrick1229** [woocommerce/woocommerce-google-analytics-integration#193] opened 2021-06-18 16:29 UTC
#### What I expected

Since a 'parent' product isn't necessarily a real product on the storefront (that would instead be assumed the variations), I wouldn't expect to see the parent product also listed within Google: 

<img width="1600" alt="Markup 2021-06-17 at 14 01 29" src="https://user-images.githubusercontent.com/19918755/122591001-5485e200-d030-11eb-82d0-ec8b453b2136.png">

#### What happened instead

The parent product, which has no set cost, was also sent over to Google, in addition to the variations.

#### Steps to reproduce the issue

Set up a variable product in WooCommerce.
Once synced you should see both the 'parent' and its' variations in Google.

-------------------

#### Additional Details

4075881-zen

Verified by @dougaitken 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by budzanowski** [comment] 2021-09-13 07:54
Hello @jrick1229!

Thank you for creating the Issue. I was able to reproduce what you are seeing. I am not sure though if this is the same scenario - if not, then please provide exact steps to reproduce as the logic behind the code may be different.

In my testing, I was able to see the parent product in the listing when I have entered its view and the child ( the variation, actual product with price ) after I have added the product to the cart and made a purchase.

I did look at the Google Analytics events API and I think there is no actual solution to this problem given how Google Analytics is constructed. In order to not have the parent items in the list, we would need to disable the _view_ event for the variable parent's product view. This would cause the problem of losing all the tracking data when the user is browsing the product.
Although the current view may be confusing because of how the stats are split between parent and variation one can still recalculate manually the Cart-to-Detail and Buy-to-Detail rate for product and its variations. Without the _view_ event, it becomes impossible to understand how well the product is Performing. Let's say that the people are selecting the parent but never go past the variation selection ( item does not go to the cart ), we would lose that information thinking that there is zero interaction with the product from the users - it would appear that it never gets selected from the list. A lot of plugin users would deem this behavior unacceptable. 

It would be great if we would be able to merge this information in some way but Google Analytics does not have this feature.

I am closing this for now. If you have any suggestions on how to solve this problem please reopen.

**Closed as completed by budzanowski** 2021-09-13 07:54 UTC

**Comment by jrick1229** [comment] 2021-09-13 12:15
Hey @budzanowski - I think you nailed it. That makes perfect sense to me!
