### ISSUE TITLE
eCommerce events are not being logged

### ISSUE THREAD

**Issue by jorgemd24** [woocommerce/woocommerce-google-analytics-integration#302] opened 2023-09-19 17:55 UTC
### Describe the bug:

It appears that events like `add_to_cart` are currently not appearing in the Google Analytics dashboard. I can confirm that the requests are being sent, and the data is correct, but for some reason, Google Analytics isn't displaying these events.

![image](https://github.com/woocommerce/woocommerce-google-analytics-integration/assets/2488994/624d83d7-7a3f-4023-a465-b47e2f67b3ac)

![image](https://github.com/woocommerce/woocommerce-google-analytics-integration/assets/2488994/7a0d0230-037f-4408-9c77-c8d9e053100c)

![image](https://github.com/woocommerce/woocommerce-google-analytics-integration/assets/2488994/6283a5b2-57fa-4d51-9da6-61cf26c59d95)

### Steps to reproduce:

1. Set up Google Analytics.
2. Add a product to the cart.
3.  Check in [Google Analytics](https://analytics.google.com/analytics) if the event is displayed

### Expected behavior:
Events should be visible in Google Analytics.

### Actual behavior:

Events are not visible in Google Analytics.

### Additional details:
p1695093861528739-slack-C7U3Y3VMY

**Comment by matrig75** [comment] 2023-09-20 07:12
Hello 👋 !

One of the website I manage is also affected by this issue. My client's website was already running GA4 tag with Woocommerce Analytics since 2022 and ecomm data was OK on GA4.  It appeared around early august, and since, we lack add2cart and purchase events.

One of my guess is the issue does not directly come from WooCommerce plugin, but in fact is related to Google "enforcing" GA4 to UA users. As a lot of users did not migrate to GA4, they tried to "summon" GA4 events with the previous tag. 

@jorgemd24 : in your screenshot, I see an event_category, although it's discontinued. It should be send as a Gtag event, with additionnal parameters (why not a category). Event actions, categories and labels are useless in GA4.

**Comment by puntope** [comment] 2023-09-20 08:07
<img width="1405" alt="Screenshot 2023-09-20 at 11 10 15" src="https://github.com/woocommerce/woocommerce-google-analytics-integration/assets/5908855/286aa5b8-a5f9-432e-a6ee-920f7a82467e">

In real time the events are being tracked. Still, I don't see anything in the event data

In the debug view, everything seems correct as well

<img width="1492" alt="Screenshot 2023-09-20 at 12 06 16" src="https://github.com/woocommerce/woocommerce-google-analytics-integration/assets/5908855/592edb64-883b-4cc0-a6a0-404a2b3794c8">

**Comment by jorgemd24** [comment] 2023-09-20 08:11
Thanks @puntope for looking at this!

I just noticed that I had the GL&A extension enabled, and it appears that GL&A was the one for sending the events. When I disable the GL&A extension, I can't see any event requests being sent.

Did you have the GL&A enabled when you were testing it?

**Comment by puntope** [comment] 2023-09-20 08:14
>  Did you have the GL&A enabled when you were testing it?

No, only WooCommerce last version 8.1.1 and WooCommerce Google Analytics Last version 1.8.5

What theme are you using? We still have this PR that I recently merged into trunk https://github.com/woocommerce/woocommerce-google-analytics-integration/pull/300. It solves some issues with the Products (Beta) Block.

**Comment by puntope** [comment] 2023-09-20 08:20
>  I can't see any event requests being sent.

Also, as a logged admin, they don't trigger. Just to be sure you're not testing the events as admin.

**Comment by jorgemd24** [comment] 2023-09-20 08:30
I tried it as Incognito and with StoreFront and Twenty Twenty theme.

I can't see any request to google. 🤔 

https://github.com/woocommerce/woocommerce-google-analytics-integration/assets/2488994/5b7d407a-107c-4b27-8028-3c62399f21f1

**Comment by puntope** [comment] 2023-09-20 08:38
For me, it's working with TT2 as well as Storefront. 
Which version of the plugin and WC are you using?

**Comment by jorgemd24** [comment] 2023-09-20 08:42
> For me, it's working with TT2 as well as Storefront.

Mmmmm 🤔 

I am using:

WC 8.1.1
And G. Analytics 1.8.5

**Comment by puntope** [comment] 2023-09-20 09:03
@matrig75  We have some issues opened in order to proceed with GA4 property migration.

https://github.com/woocommerce/woocommerce-google-analytics-integration/issues/268

I'm placing this on hold, as I need to wait 48h to see the events.

**Comment by matrig75** [comment] 2023-09-20 09:17
> @matrig75 We have some PRs in order to proceed with GA4 property migration.

I apologize for any misunderstanding, what's PRs ?

**Comment by puntope** [comment] 2023-09-20 09:19
> I apologize for any misunderstanding, what's PRs ?

Sorry, @matrig75 my bad. I meant that we have some issues opened. We will work on it soon. We don't have any PR (pull request) with the code update yet.

**Comment by mikkamp** [comment] 2023-09-20 11:57
> I just noticed that I had the GL&A extension enabled, and it appears that GL&A was the one for sending the events. When I disable the GL&A extension, I can't see any event requests being sent.

Just to clarify this behaviour. In the screenshots you can also see your event with `send_to=GLA`
![image](https://github.com/woocommerce/woocommerce-google-analytics-integration/assets/11388669/2590ff6f-2782-4fba-92c0-6062ae7fa848)

If you have GLA active with an Ads account connected then it will send those analytics to your Ads account, they would be separate from any event tracking that's being sent by the Google Analytics extension.

As for tracking in Google Analytics, you can enable / disable most events. Can you confirm they are all enabled in the settings:
![image](https://github.com/woocommerce/woocommerce-google-analytics-integration/assets/11388669/0ae69344-311a-41a3-bbba-3a209af1240d)

**Comment by jorgemd24** [comment] 2023-09-20 17:10
> As for tracking in Google Analytics, you can enable / disable most events. Can you confirm they are all enabled in the settings:

@mikkamp, yes, it turned out to be an issue on my end. I didn't have the correct settings configured. I checked this with @puntope, and we could see the data in real-time, although it wasn't appearing in the dashboard. We suspect that there might be a delay before the real-time data shows up in the "Purchase journey" section. 

We've decided to temporarily put this "on-hold" to allow for some time to see if the data eventually appears in the "Purchase journey" section.

**Comment by puntope** [comment] 2023-09-25 14:28
Hello there @matrig75 

I was checking after the weekend the results in my Analytics account and I can see perfectly the events being recorded:

<img width="1721" alt="Screenshot 2023-09-25 at 18 20 27" src="https://github.com/woocommerce/woocommerce-google-analytics-integration/assets/5908855/52665b4d-252e-4f47-85e9-1b0efc7e4ddd">

Can you please test the next in your store? 

- You are using the last version of the plugin (both Woo and Analytics Integration)
- Your Google Analytics Tracking ID  in WooCommerce - Settings - Integration - Google Analytics is correctly set
- All the options in WooCommerce - Settings - Integration - Google Analytics are checked
- You are doing your tests without being logged as admin.
- You can see the events being tracked in real-time in Google Analytics
- After 48 you can see the events in the Purchase Journey

Let us know so we can continue troubleshooting your case.

**Comment by dpanfili** [comment] 2023-10-23 15:05
This still is an issue for me.

**Comment by tomalec** [comment] 2023-10-25 18:44
@dpanfili Could you please provide more details? Like your settings, [system status report](https://woocommerce.com/document/how-to-review-your-woocommerce-system-status/), logs, screenshots.
Have you checked all the things mentioned above(https://github.com/woocommerce/woocommerce-google-analytics-integration/issues/302#issuecomment-1733827160)?

None of us developers was able to reproduce the problem, so we need some hints on your setup.

You can also check and reach out to our community forum https://wordpress.org/support/plugin/woocommerce-google-analytics-integration/
There you may check if there are other people with a setup similar to yours. Plus, get feedback and support from other users and our support engineers.

**Comment by tomalec** [comment] 2023-11-06 15:36
I'm closing the issue as non-reproducible for now.
Please feel free to reopen with reproduction steps and more details if you still face it :)

**Closed as completed by tomalec** 2023-11-06 15:36 UTC
Labels: needs feedback
