### ISSUE TITLE
Multiple Instances of click & pageview events

### ISSUE THREAD

**Issue by caljp** [woocommerce/woocommerce-google-analytics-integration#107] opened 2018-01-04 16:52 UTC
Hi, I'm using the plugin across several sites and it's working great other than that the js output on my page is appearing 3 times on each page:

`$( '.add_to_cart_button:not(.product_type_variable, .product_type_grouped)' ).click( function() {
  | ga('send', 'event', 'Products', 'Add to Cart', ($(this).data('product_sku')) ? ($(this).data('product_sku')) : ('#' + $(this).data('product_id')));
  | });
  |  
  |  
  | ga( 'send', 'pageview' );`

You can see the issue at https://manualhandlingtrainingatwork.co.uk. The code outputs 3 times, but the prefixing comments for the plugin only outputs the first two times.

It's not causing multiple pageview's to fire, but just a bit curious as to why this might be happening?

**Comment by laurendavissmith** [comment] 2018-03-06 20:50
@caljp I've been unable to reproduce this on my end. I see on your site that it's appearing in multiple locations within the footer as well. It is possible another extension you have installed is conflicting with the Google Analytics code. Closing for now but feel free to reopen if you have some steps we can follow to reproduce on our end.

If you can help us find some steps to be able to reproduce we can troubleshoot further.

**Comment by laurendavissmith** [comment] 2018-03-07 22:43
After looking into this further I see other JavaScript being duplicated in your sites footer. It looks like `wp_footer` is being called twice somewhere in your theme possibly.

**Closed by laurendavissmith** 2018-03-07 22:43 UTC
Labels: [Pri] Low, [Type] Bug

**Comment by caljp** [comment] 2018-03-08 08:21
Hi Lauren,

Ah sorry, my bad - thanks for taking the time to look into it.

Cal
