### ISSUE TITLE
Product id reading issue for variable product add-to-cart(AJAX)

### ISSUE THREAD

**Issue by sagarnasit** [woocommerce/woocommerce-google-analytics-integration#451] opened 2024-07-12 17:34 UTC
### Describe the bug:
The plugin displays an error when clicking the add-to-cart button for the variable product. This occurs only when using the ajax add-to-cart button.

### Steps to reproduce:
1. Activate plugin and set GA tracking id.
1. Use AJAX for add-to-cart products.
2. Add variable product with multiple variations. 
3. On the single product page, choose a product variation from the dropdown and then click on the add-to-cart button.

### Expected behavior:
The plugin should be able to read the product id. 

### Actual behavior:
The plugin is not able to read product id for variable products.

### Additional details:
Plugin cannot retrieve the product id from the button element for a variable product because the variable product id is set via a hidden input rather than the button value attribute.

Screenshot:
<img width="1094" alt="image" src="https://github.com/user-attachments/assets/a1b1c692-ecbb-4be4-8f3c-f46aa4d91c5a">

**Comment by tomalec** [comment] 2024-07-16 22:02
Hi @sagarnasit :) 
Thanks for reporting an issue.
Unfortunately, I was not able to reproduce it. Have you tested it with only WooCommerce and Google Analytics for WooCommerce, without any other extensions? Or maybe you could share more detailed steps to reproduce or a link to the shop with such an issue?

**Comment by sagarnasit** [comment] 2024-07-17 09:07
Hi @tomalec 

I have tested on fresh setup with WooCommerce and Google Analytics for WooCommerce plugins. I noticed `Google Analytics Tracking ID` settings field should be configured and it does not work if you logged in as admin. 

Apart from that, the only condition is to use AJAX for add-to-cart. I'm using following script to handle AJAX.

```JS
jQuery(function ($) {

	// Open external product in new tab
	$( document ).find( '.product.product-type-external form.cart' ).attr( 'target', '_blank' );

	const addToCart = function ( e ) {
		e.preventDefault();

		const form = $( this ),
			button = form.find( '.single_add_to_cart_button' ),
			quantity = form.find( 'input[type="number"].qty' ).val(),
			isVariation = form.hasClass( 'variations_form' ) ?? false,
			variationValue = form
				.find( 'input[type="hidden"].variation_id' )
				.val(),
			attributeValue = form.find( 'select[name="attribute_amount"]' ).val();

		const data = {};
		data.product_id = isVariation
			? Number( form.data( 'product_id' ) )
			: Number( button.val() );
		data.quantity = quantity ? Number( quantity ) : 1;

		if ( isVariation && variationValue ) {
			data.product_id = Number( variationValue );
		}

		if ( isVariation && attributeValue ) {
			data.attribute_amount = attributeValue;
		}

		// Abort if don't have required data
		if ( ! data.product_id || ! data.quantity ) {
			return;
		}

		button.removeClass( 'added' );
		button.addClass( 'loading' );

		$( document.body ).trigger( 'adding_to_cart', [ button, data ] );

		$.ajax( {
			type: 'POST',
			url: woocommerce_params.wc_ajax_url
				.toString()
				.replace( '%%endpoint%%', 'add_to_cart' ),
			data: data,
			success: function ( response ) {
				if ( ! response ) {
					return;
				}

				// Redirect to cart option
				if ( wc_add_to_cart_params.cart_redirect_after_add === 'yes' ) {
					window.location = wc_add_to_cart_params.cart_url;
					return;
				}

				$( document.body ).trigger( 'added_to_cart', [
					response.fragments,
					response.cart_hash,
					button,
				] );
			},
			complete: function () {
				form.unblock();
			},
		} );
	};

	$( document ).on( 'submit', '.product:not(.product-type-external) form.cart', addToCart );
} );

```

**Comment by tomalec** [comment] 2024-07-17 18:23
Thanks for the details.

> I noticed Google Analytics Tracking ID settings field should be configured and it does not work if you logged in as admin.

Yes, Tracking ID is required for most of the extension functionality. Also, this is the desired behavior not to track admin action not to skew the analytics reports.

> Apart from that, the only condition is to use AJAX for add-to-cart. I'm using following script to handle AJAX.

Do I read it right? This is not the native WooCommerce AJAX behavior enabled by the settings:
![image](https://github.com/user-attachments/assets/b55b5d16-230b-4902-9bc0-10adb3adc7e8)

But your custom code, correct?


If so, you need to fix that snippet to provide the product data:
```js
button.dataset.product_id = data.product_id;
```
Before firing `added_to_cart` event.

Please let me know if that helps.

**Comment by sagarnasit** [comment] 2024-07-17 19:41
@tomalec Yes, it's a custom code that I'm using.

I tried your suggestion but it did not work with the following error.

```
TypeError: Cannot set properties of undefined (setting 'product_id')
```

On a simple product, the add-to-cart button is expected to have a value attribute with the product_id. I tried the following, which worked for me, but I'm not sure if that's the correct approach.

```
button.attr('value', data.product_id);
```

**Comment by tomalec** [comment] 2024-07-17 19:59
Sorry, I was using the native DOM API. To set the dataset for the jQuery object, you need to use [jQuery API](https://api.jquery.com/data/):
```js
button.data( 'product_id', data.product_id );
```

**Comment by sagarnasit** [comment] 2024-07-18 18:29
@tomalec It's showing the same error using jQuery API too.

**Comment by tomalec** [comment] 2024-07-18 21:24
Maybe then stick to vanilla API and just fetch the native object out of the jQuery collection:
```js
button[0].dataset.product_id = data.product_id;
```

**Comment by tomalec** [comment] 2024-07-23 19:45
I'm closing this issue as answered. If it still does not work, feel free to reopen.

**Closed as completed by tomalec** 2024-07-23 19:45 UTC

**Comment by yennmorrigan** [comment] 2025-09-25 21:34
I also encountered this problem. Obviously, your script breaks the code when it tries to get dataset.product_id || .value for a product with a variable type, because a variable type cannot have a value in advance.

<img width="1050" height="208" alt="Image" src="https://github.com/user-attachments/assets/24edf0dc-0ac7-4052-aed3-6df59107e94c" />

Button html (ajax add to cart)

<img width="709" height="29" alt="Image" src="https://github.com/user-attachments/assets/e6a6f98c-2551-42e0-8aa6-9e4074a28894" />

Of course, the dataset.product_id and node[0].value is empty.

<img width="1050" height="174" alt="Image" src="https://github.com/user-attachments/assets/276e9e82-5cb3-4863-8e45-9ff735941c21" />

But because an error is thrown, the rest of the code breaks, and I, for example, cannot open a popup window after adding a product to the cart because of this, the logic for opening which is already implemented in another plugin.

@tomalec

**Comment by triple0t** [comment] 2025-09-26 11:40
Hi @yennmorrigan 

Could you please provide a step-by-step guide on how to reproduce this error?

I don't get an error when adding a variable product to cart with just the WooCommerce and the Google Analytics for WooCommerce plugin.

Thank you.

**Comment by yennmorrigan** [comment] 2025-09-26 12:40
@triple0t 
Yes, of course.
I'll try to explain the problem again.
I have a Jet Popup plugin that opens a popup after adding a product to the cart.
Your plugin tracks clicks on the add to cart button, and if the button cannot get the product ID (see comment above), it throws an error. 
Here is an example of a button layout for a non-variable product. 

<img width="394" height="69" alt="Image" src="https://github.com/user-attachments/assets/6b90116c-4ba0-43f7-86c8-1eb0825ce52a" />

The script in your plugin will take the value attribute, and then the error will not be thrown, and Jet Popup will successfully open the popup.
But if I load the page of a variable product, here is the button layout

<img width="573" height="52" alt="Image" src="https://github.com/user-attachments/assets/e69db729-b86d-4250-9854-db90de4ff931" />
The script will not find either the value or the data-product-id and will throw an error, which will prevent the popup window from opening.

I think my problem is compatible with this issue https://github.com/woocommerce/woocommerce-google-analytics-integration/issues/475
