### ISSUE TITLE
Enhanced ecommerce with gtag.js

### ISSUE THREAD

**Issue by msdesign21** [woocommerce/woocommerce-google-analytics-integration#102] opened 2017-10-05 22:06 UTC
Today we had a customer interview with TinyFrog who said they would love to see the new eCommerce enhanced tag implemented "for tracking product interaction, product lists interaction, as well as order flow."

https://developers.google.com/analytics/devguides/collection/gtagjs/enhanced-ecommerce

Google docs describes this as: 

> Enhanced ecommerce enables the measurement of user interactions with products on ecommerce websites across the user's shopping experience, including product selections, product detail views, adding a product to a shopping cart, initiating the checkout process, purchases, and refunds.

Sounds like this could add a lot of value to eCommerce statistics. I'm not very familiar with this area, so I'll leave it in your good hands to review/comment.

**Comment by jaxne** [comment] 2017-11-08 02:33
Thanks for posting this msdesign21.  I too am working with an online store that is using Monster Insights Pro with the ecommerce add-on.  However, it's using an older GA tracking code implementation and Google suggested using gtag.js instead too.  So now I'm waiting to hear back from Monster Insights or hopefully, SkyVerge will bring an update to the table with their WooCommerce GA tracking extension.

**Comment by laurendavissmith** [comment] 2018-03-07 22:07
@msdesign21 this seems like it could be a duplicate of #77 or did you have something additional in mind?

**Comment by Tobias-Conrad** [comment] 2018-03-09 10:01
thank you very much.
My idea is to make woocommerce tracking free and Premium plugin compatible with Google Analytics Dashboard for WordPress. (https://de.wordpress.org/plugins/google-analytics-dashboard-for-wp/)

**Comment by msdesign21** [comment] 2018-03-09 16:04
@laurendavissmith I don't know enough about the topic to say. Was just trying to relay feedback we heard in our customer interview. If it seems to be the same then I trust your lead.

**Comment by zwiesman31** [comment] 2018-07-02 17:53
I see this had a PR over 3 months ago. Any update on an ETA for implementation of this @bor0? Thanks!

**Comment by bor0** [comment] 2018-07-02 17:58
@zwiesman31 this had a PR which needs some testing, but I don't know how it will stand with our current priorities on our roadmap, given that this was a hack week project.

cc @laurendavissmith @avivapinchas for more details

**Comment by dougaitken** [comment] 2020-09-14 13:01
As a note, I came across a similar request here - 

Related Ideas board request - https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/34485613-enhanced-ecommerce-with-gtag-js - please upvote that Idea

**Comment by findingsimple** [comment] 2020-12-20 00:59
We've released version 1.5.0 with support for global site tags (gtag.js)

**Closed by findingsimple** 2020-12-20 00:59 UTC
Labels: [Pri] High, [Type] Enhancement
