### ISSUE TITLE
Missing revenues in GA

### ISSUE THREAD

**Issue by corsonr** [woocommerce/woocommerce-google-analytics-integration#66] opened 2015-10-15 13:50 UTC
A few people have been complaining about having a difference around 10 to 15% between revenues in GA and in WC.

I have no clue what could explain that. Any feedback on this would be great.

@BFTrick 

https://woothemes.zendesk.com/agent/tickets/344152

**Comment by BFTrick** [comment] 2015-10-15 17:35
This integration uses JavaScript so if users have JS disabled those orders won't appear in GA. But that's 1-2% of users not 10-15%

Gonna need more information @corsonr

**Comment by lkraav** [comment] 2015-10-15 20:41
Thoughts on using Measurement Protocol instead? There's at least one plugin I know that's already doing this https://github.com/ronalfy/wordpress-gravity-forms-event-tracking/issues/6

**Comment by corsonr** [comment] 2015-10-20 07:35
I haven't said that 10-15% of users experience this issue, I said that the revenues difference between GA and WC is 10-15% ;-)

In other words 10 to 15% of transactions aren't sent to GooGle Analytics.

**Comment by BFTrick** [comment] 2015-10-21 15:32
I know at scale Google Analytics doesn't record everything but uses fancy math to predict sales / visits / etc from a sample. Does this happen to be on a really large site @corsonr ?

**Comment by corsonr** [comment] 2015-10-23 06:52
I just asked the customer to provide more details on sales volume @BFTrick

**Comment by allendav** [comment] 2015-11-18 23:31
See also this thread : https://wordpress.org/support/topic/ga-revenue-woocommerce-revenue-mismatched

**Comment by mike3run** [comment] 2015-11-27 13:10
I could think that people with AdBlock installed block tracking codes automatically hence the mismatch.

**Comment by tnog** [comment] 2015-11-29 22:49
One of our clients just noticed a larger discrepancy between their WC order info and the GA ecommerce data for the month of October. We're talking about a 25% difference on a total sales volume of +$40,000 for the month.

After further investigation, I noticed that we we're specifically missing orders for two products for which we created a custom thank you page. It seems that the GA script (they're using the regular GA script, not universal) for this endpoint doesn't include any transaction data. Can you specify additional custom endpoints for the ecommerce tracking code besides just the default thank you page?

**Comment by allendav** [comment] 2015-12-11 23:06
@nabsul - would you take a look? - @tnog 's comment immediately above suggests at least one way the extension might miss sales

**Comment by nabsul** [comment] 2015-12-22 16:57
I've started working on a fix that could potentially get all the data to google, even if the user never goes to the thank you pages. There are still a couple of technical details about the javascript I need to figure out, but I should have a solution in the coming days.

**Comment by BFTrick** [comment] 2016-01-04 17:38
Hey @nabsul how is this coming?

**Comment by nabsul** [comment] 2016-01-08 15:51
I got stuck on how to properly test this, and then distracted by other issues. I'll probably get back to this early next week.

**Comment by tnog** [comment] 2016-01-12 22:11
Nabeel, have you thought using a server side solution instead of using
javascript for the event tracking? This would work without needing to
redirect to any specific page.
https://github.com/dancameron/server-side-google-analytics

-----------
Takahiro Noguchi
ph: +1 510.213.8252
skype: takahiro.noguchi

"...seek and learn to recognize who and what, in the midst of the inferno,
are not inferno, then make them endure, give them space."

         ~Italo Calvino, from "Invisible Cities"

**Comment by nabsul** [comment] 2016-01-13 18:05
I *JUST* thought of that option a couple of days ago. I think you're right, this is the right way to do this.

**Comment by gp0** [comment] 2016-02-05 19:46
Any updates on this?

**Comment by nabsul** [comment] 2016-02-06 01:07
I don't have much more to report on this, except that the server-side approach is a feature of https://github.com/woothemes/woocommerce-google-analytics-pro so we probably don't want to implement it here (please confirm with @BFTrick).

It looks like the only thing we could do is figure out a way to generate the javascript for the custom thank-you pages, and not just the default. But this wouldn't completely solve the problem. I haven't had a chance to actually develop anything on this topic.

**Comment by BFTrick** [comment] 2016-02-08 17:51
> I don't have much more to report on this, except that the server-side approach is a feature of https://github.com/woothemes/woocommerce-google-analytics-pro so we probably don't want to implement it here

Correct. For right now since we already have one implementation of the server side code let's keep it there. I don't think this is related to the 1-2% of users that don't have JS. I think there's something else going on.

**Comment by nabsul** [comment] 2016-02-08 20:10
The causes we have come up with are:
- User pays for item and never returns to the thank you page
- User returns to the thank you page, but it's set to a custom page that doesn't generate the JS that's needed to track the purchase

**Comment by galbaras** [comment] 2016-03-11 03:54
I have several kinds of discrepancies, which cannot be explained by the causes above. Specifically:

1. I track sales goals as visits to pages starting matching the regular expression "^/checkout/order-received/". There are more goal completions than transactions

2.  The number of sales goal completions is **higher** than the WC orders for the matching period

3. The number of transactions is **lower** than the WC orders

4. The revenue captured in Analytics is **higher** than what's in WC

Having JS turned off should make goal completions, transactions and revenue lower, but never higher, than what WC reports.

Similarly, if buyers don't display the thank you page, all the numbers in Analytics should be lower, but never higher, than what WC reports.

I don't use a custom thank you page, which excludes this cause for me.

I hope this helps,
Gal

**Comment by ankit7** [comment] 2016-03-30 18:57
Ecommerce tracking seems to be not working for my stores.

**Comment by galbaras** [comment] 2016-03-31 02:10
@ankit7 perhaps you can elaborate a little on this? See some examples above.

**Comment by qfrery** [comment] 2016-05-25 15:04
Hi @nabsul @BFTrick,

I can't find anything about a server-side approach here https://docs.woothemes.com/document/woocommerce-google-analytics-pro/
Are you sure it actually does that ?

Thanks

**Comment by galbaras** [comment] 2016-05-26 00:41
@nabsul @BFTrick any feedback on my reply from (OMG) March 11? I'd say that since the free plugin is there, it might as well work and let the pro version be used for extra stuff. In fact, assuming the pro plugin is maintained by the same team, this is a poor show of quality...

**Comment by nabsul** [comment] 2016-05-27 17:08
Sorry guys, I only briefly worked on this before being reassigned to another project. I haven't worked on the pro extension at all. I only got as far as identifying the two potential causes (comment Feb 8).

**Comment by nabsul** [comment] 2016-05-27 17:10
@gedex ?

**Comment by BFTrick** [comment] 2016-05-31 16:18
Hey @gedex 

This won't solve the problem entirely - but is is possible to take care of this issue?

> I noticed that we're specifically missing orders for two products for which we created a custom thank you page. It seems that the GA script (they're using the regular GA script, not universal) for this endpoint doesn't include any transaction data. Can you specify additional custom endpoints for the ecommerce tracking code besides just the default thank you page?

Some way for someone who uses a custom thank you page or something like that to still send data to GA?

This a hard issue to diagnose... the best way forward might be to have people submit support tickets with specific orders missing in GA but showing in WC. Then we can get admin credentials and look into why those orders failed. And please leave a reference in your ticket to this issue.

**Comment by galbaras** [comment] 2016-06-01 01:45
I think the issue will be a lot easier when someone who knows the code will guide us. Like I said before, I don't use a custom thank you page, but knowing where the plugin hooks into WooCommerce can help a great deal.

**Comment by dkjensen** [comment] 2016-06-21 17:40
@qfrery Check out the FAQ on the documentation - https://docs.woothemes.com/document/woocommerce-google-analytics-pro/#section-5

**Comment by galbaras** [comment] 2016-06-22 00:37
@dkjensen I may be blind, but I can't find any mention of server-side tracking there.

Either way, it doesn't solve the problem of mismatched reporting. If something is tracked, then the information for it should be available to all the Analytics reports and yield the same totals.

**Comment by bor0** [comment] 2018-03-08 11:07
I confirm pro has server-side tracking. See:
https://github.com/woocommerce/woocommerce-google-analytics-pro/blob/bd8edf27701a34fc03702dcdf775770369a18cd4/includes/class-sv-wc-tracking-integration.php#L81-L237

For each of those event, we call `WC_Google_Analytics_Pro_Integration::api_record_event` which eventually calls `track_event` from Google's library.

**Closed by bor0** 2018-03-08 11:07 UTC
Labels: [Pri] Low, [Type] Bug
